#!/bin/bash

# Generate index.html files for each directory to enable browsing
generate_listing() {
    local dir="$1"
    local rel_path="${dir#./}"
    
    # Skip if this is the root and index.html already exists from template
    if [ "$rel_path" = "" ] || [ "$rel_path" = "." ]; then
        return
    fi
    
    cat > "$dir/index.html" <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Index of /$rel_path</title>
    <meta charset="utf-8">
    <style>
        body { 
            font-family: monospace; 
            margin: 20px;
            background-color: #fff;
            color: #333;
        }
        h1 { 
            font-size: 1.5em; 
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        a { 
            text-decoration: none; 
            color: #0366d6; 
        }
        a:hover { 
            text-decoration: underline; 
        }
        .dir::before { content: "📁 "; }
        .file::before { content: "📄 "; }
        .deb::before { content: "📦 "; }
        table { 
            border-collapse: collapse; 
            width: 100%; 
            margin-top: 20px;
        }
        td { 
            padding: 5px 10px; 
            border-bottom: 1px solid #eee;
        }
        tr:hover { 
            background-color: #f6f8fa; 
        }
        th {
            text-align: left;
            padding: 5px 10px;
            background-color: #f0f0f0;
            border-bottom: 2px solid #ddd;
        }
        .size { text-align: right; }
        .date { color: #666; }
        hr { border: 0; border-top: 1px solid #ddd; }
        .footer { 
            margin-top: 20px; 
            color: #666; 
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <h1>Index of /$rel_path</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th class="size">Size</th>
                <th>Modified</th>
            </tr>
        </thead>
        <tbody>
EOF

    # Parent directory link
    if [ "$rel_path" != "" ] && [ "$rel_path" != "." ]; then
        echo '            <tr><td class="dir"><a href="../">Parent Directory</a></td><td class="size">-</td><td class="date">-</td></tr>' >> "$dir/index.html"
    fi
    
    # List directories first
    find "$dir" -maxdepth 1 -type d ! -path "$dir" ! -name ".*" -printf '%f\n' 2>/dev/null | sort | while read -r item; do
        echo "            <tr><td class=\"dir\"><a href=\"$item/\">$item/</a></td><td class=\"size\">-</td><td class=\"date\">Directory</td></tr>" >> "$dir/index.html"
    done
    
    # List files
    find "$dir" -maxdepth 1 -type f ! -name "index.html" ! -name ".*" -printf '%f\t%s\t%TY-%Tm-%Td %TH:%TM\n' 2>/dev/null | sort | while IFS=$'\t' read -r name size date; do
        # Convert size to human readable
        local human_size
        if [ "$size" -gt 1073741824 ]; then
            human_size="$(awk "BEGIN {printf \"%.1f\", $size/1073741824}")G"
        elif [ "$size" -gt 1048576 ]; then
            human_size="$(awk "BEGIN {printf \"%.1f\", $size/1048576}")M"
        elif [ "$size" -gt 1024 ]; then
            human_size="$(awk "BEGIN {printf \"%.1f\", $size/1024}")K"
        else
            human_size="${size}B"
        fi
        
        # Use special icon for .deb files
        local css_class="file"
        if [[ "$name" == *.deb ]]; then
            css_class="deb"
        fi
        
        echo "            <tr><td class=\"$css_class\"><a href=\"$name\">$name</a></td><td class=\"size\">$human_size</td><td class=\"date\">$date</td></tr>" >> "$dir/index.html"
    done
    
    cat >> "$dir/index.html" <<EOF
        </tbody>
    </table>
    <hr>
    <div class="footer">
        <p><em>APT Repository Browser - Generated by GitHub Actions</em></p>
        <p><a href="/">← Back to Repository Home</a></p>
    </div>
</body>
</html>
EOF
}

# Generate listings for all directories except root and hidden directories
find . -type d ! -path '*/\.*' ! -path '.' | sort | while read -r dir; do
    echo "Generating listing for: $dir"
    generate_listing "$dir"
done

echo "✓ Directory listings generated successfully"
